export class Item {
  constructor(
    public itemID: string,
    public businessID: string,
    public shipperID: string,
    public itemNumber: string,
    public itemName: string,
    public htsCode: string,
    public fnsku: string,
    public asin: string,
    public weight: number,
    public weightUnit: string,
    public unitPrice: string,
    public currency: string,
    public updatedOn: string,
    public createdOn: string,
    // public ItemID: string,
    // public BusinessID: string,
    // public ShipperID: string,
    // public ItemNumber: string,
    // public ItemName: string,
    // public HTSCode: string,
    // public FNSKU: string,
    // public ASIN: string,
    // public Weight: number,
    // public WeightUnit: string,
    // public UnitPrice: string,
    // public Currency: string,
    // public UpdatedOn: string,
    // public CreatedOn: string,
  ) { }
}